services:
  - type: web
    name: powerup-streamlit-app
    env: python
    plan: free
    buildCommand: ""
    startCommand: streamlit run main.py --server.port=10000 --server.enableCORS false
    envVars:
      - key: PYTHON_VERSION
        value: "3.10"